export const DFORM_COMP_NAME = [
  'addressPicker',
  'coverRadio',
  'extraInput',
  'multiplePicker',
  'dformInput',
  'dformSelect',
  'dformPicker',
  'dformSwitch',
  'dformTextArea',
  'dformDatePicker',
  'dformRadio',
  'dformCheckBox',
  'dformImagePicker',
  'dformCustom',
  'dformText',
  'dformFile',
  'rangeDatePicker',
];

export const NO_SUPPORT_VERTICAL = ['switch', 'NomarSwitch'];

export const DFORM_COMP_DETAULT = {
  addressPicker: { positionType: 'horizontal' },
  coverRadio: { positionType: 'horizontal' },
  extraInput: { positionType: 'vertical' },
  multiplePicker: { positionType: 'horizontal' },
  input: { positionType: 'horizontal' },
  select: { positionType: 'horizontal' },
  picker: { positionType: 'horizontal' },
  switch: { positionType: 'horizontal' },
  area: { positionType: 'horizontal' },
  date: { positionType: 'horizontal' },
  radio: { positionType: 'horizontal' },
  checkbox: { positionType: 'vertical' },
  image: { positionType: 'vertical' },
  custom: { positionType: 'vertical' },
  text: { positionType: 'horizontal' },
  file: { positionType: 'vertical' },
  rangeDatePicker: { positionType: 'vertical' },
  dformInput: { positionType: 'horizontal' },
  dformSelect: { positionType: 'horizontal' },
  dformPicker: { positionType: 'horizontal' },
  dformSwitch: { positionType: 'horizontal' },
  dformTextArea: { positionType: 'horizontal' },
  dformDatePicker: { positionType: 'horizontal' },
  dformRadio: { positionType: 'horizontal' },
  dformCheckBox: { positionType: 'vertical' },
  dformImagePicker: { positionType: 'vertical' },
  dformCustom: { positionType: 'vertical' },
  dformText: { positionType: 'horizontal' },
  dformFile: { positionType: 'vertical' },
} as { [key: string]: { positionType: 'vertical' | 'horizontal' } };
