export const DFORM_COMP_NAME = [
  'AddressPicker',
  'CoverRadio',
  'ExtraInput',
  'MultiplePicker',
  'NomarInput',
  'NomarSelect',
  'NomarPicker',
  'NomarSwitch',
  'NomarTextArea',
  'NomarDatePicker',
  'NomarRadio',
  'NomarCheckBox',
  'NomarImagePicker',
  'NomarCustom',
  'NomarText',
  'NomarFile',
  'RangeDatePicker',
];

export const DFORM_COMP_DETAULT = {
  addressPicker: { positionType: 'horizontal' },
  coverRadio: { positionType: 'horizontal' },
  extraInput: { positionType: 'vertical' },
  multiplePicker: { positionType: 'horizontal' },
  input: { positionType: 'horizontal' },
  select: { positionType: 'horizontal' },
  picker: { positionType: 'horizontal' },
  switch: { positionType: 'horizontal' },
  area: { positionType: 'horizontal' },
  date: { positionType: 'horizontal' },
  radio: { positionType: 'horizontal' },
  checkbox: { positionType: 'vertical' },
  image: { positionType: 'vertical' },
  custom: { positionType: 'vertical' },
  text: { positionType: 'horizontal' },
  file: { positionType: 'vertical' },
  rangeDatePicker: { positionType: 'vertical' },
} as { [key: string]: { positionType: 'vertical' | 'horizontal' } };
